// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp_wr8_goj_OTAt_nuizYvswpild6MtoE',
    appId: '1:588250998348:web:9246fd51f31e53b37636e9',
    messagingSenderId: '588250998348',
    projectId: 'flutter-booking-a640d',
    authDomain: 'flutter-booking-a640d.firebaseapp.com',
    storageBucket: 'flutter-booking-a640d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9AB7lY01vKT_F_823Sgj7pbSOltojuD0',
    appId: '1:588250998348:android:f5106ef09bfffbbd7636e9',
    messagingSenderId: '588250998348',
    projectId: 'flutter-booking-a640d',
    storageBucket: 'flutter-booking-a640d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5e4PwUEEbHBYb8jOgfACnc9caMrRFAgI',
    appId: '1:588250998348:ios:5fa54202851ed3d97636e9',
    messagingSenderId: '588250998348',
    projectId: 'flutter-booking-a640d',
    storageBucket: 'flutter-booking-a640d.firebasestorage.app',
    iosBundleId: 'com.example.flutterBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5e4PwUEEbHBYb8jOgfACnc9caMrRFAgI',
    appId: '1:588250998348:ios:5fa54202851ed3d97636e9',
    messagingSenderId: '588250998348',
    projectId: 'flutter-booking-a640d',
    storageBucket: 'flutter-booking-a640d.firebasestorage.app',
    iosBundleId: 'com.example.flutterBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp_wr8_goj_OTAt_nuizYvswpild6MtoE',
    appId: '1:588250998348:web:bde98079208193ff7636e9',
    messagingSenderId: '588250998348',
    projectId: 'flutter-booking-a640d',
    authDomain: 'flutter-booking-a640d.firebaseapp.com',
    storageBucket: 'flutter-booking-a640d.firebasestorage.app',
  );
}
