// <auto-generated />
using System;
using Gestion_Stock.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestion_Stock.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260419212643_AddUniteAndCafeData")]
    partial class AddUniteAndCafeData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gestion_Stock.Models.Alerte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstLue")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProduitId")
                        .HasColumnType("int");

                    b.Property<string>("TypeAlerte")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DateCreation");

                    b.HasIndex("ProduitId");

                    b.ToTable("Alertes");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Café, thé, chocolat, infusions",
                            Nom = "Boissons chaudes"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lait, crème, beurre, fromages",
                            Nom = "Produits laitiers"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Farine, sucre, sel, riz, pâtes",
                            Nom = "Farines & Céréales"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Poulet, bœuf, jambon, merguez",
                            Nom = "Viandes & Charcuterie"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Légumes frais, fruits de saison",
                            Nom = "Fruits & Légumes"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Huile d'olive, vinaigre, épices, sauces",
                            Nom = "Huiles & Condiments"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Jus, sodas, eau minérale, sirops",
                            Nom = "Boissons froides"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Œufs, levure, chocolat, vanille",
                            Nom = "Pâtisserie & Desserts"
                        });
                });

            modelBuilder.Entity("Gestion_Stock.Models.CommandeAchat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeId")
                        .HasColumnType("int");

                    b.Property<decimal>("FraisLivraison")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("LivraisonId")
                        .HasColumnType("int");

                    b.Property<decimal>("SousTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalFacture")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DateCommande");

                    b.HasIndex("EmployeId");

                    b.HasIndex("LivraisonId");

                    b.ToTable("CommandesAchat");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Commercial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Commission")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Commerciaux");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Commission = 3.5m,
                            Nom = "Karim Mansouri",
                            Region = "Grand Tunis"
                        },
                        new
                        {
                            Id = 2,
                            Commission = 4.0m,
                            Nom = "Sonia Gharbi",
                            Region = "Sahel"
                        });
                });

            modelBuilder.Entity("Gestion_Stock.Models.Employe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Employes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ahmed.bensalah@cafe-resto.tn",
                            NomComplet = "Ahmed Ben Salah",
                            Note = "Responsable des achats et approvisionnement"
                        },
                        new
                        {
                            Id = 2,
                            Email = "fatma.trabelsi@cafe-resto.tn",
                            NomComplet = "Fatma Trabelsi",
                            Note = "Gestionnaire de stock et inventaire"
                        },
                        new
                        {
                            Id = 3,
                            Email = "m.chaabane@cafe-resto.tn",
                            NomComplet = "Mohamed Chaabane",
                            Note = "Chef de cuisine - contrôle qualité"
                        });
                });

            modelBuilder.Entity("Gestion_Stock.Models.Fournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Fournisseurs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresse = "Zone Industrielle, Tunis",
                            Email = "commandes@cafepremium.tn",
                            Nom = "Café Premium Tunisie",
                            Telephone = "71 234 567"
                        },
                        new
                        {
                            Id = 2,
                            Adresse = "Route de Bizerte, Mateur",
                            Email = "ventes@laiterie-nord.tn",
                            Nom = "Laiterie du Nord",
                            Telephone = "72 345 678"
                        },
                        new
                        {
                            Id = 3,
                            Adresse = "Marché de Gros, Sfax",
                            Email = "contact@grossiste-benali.tn",
                            Nom = "Grossiste Alimentaire Ben Ali",
                            Telephone = "73 456 789"
                        },
                        new
                        {
                            Id = 4,
                            Adresse = "Rue du Marché, Sousse",
                            Email = "info@boucherie-centrale.tn",
                            Nom = "Boucherie Centrale",
                            Telephone = "74 567 890"
                        });
                });

            modelBuilder.Entity("Gestion_Stock.Models.FournisseurProduit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DelaiLivraisonJours")
                        .HasColumnType("int");

                    b.Property<int>("FournisseurId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrixAchat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProduitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FournisseurId");

                    b.HasIndex("ProduitId");

                    b.ToTable("FournisseurProduits");
                });

            modelBuilder.Entity("Gestion_Stock.Models.LigneCommande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommandeAchatId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProduitId")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommandeAchatId");

                    b.HasIndex("ProduitId");

                    b.ToTable("LignesCommande");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Livraison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommercialId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateLivraison")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NoteAvis")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CommercialId");

                    b.ToTable("Livraisons");
                });

            modelBuilder.Entity("Gestion_Stock.Models.MouvementStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommandeAchatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateMouvement")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProduitId")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<string>("Raison")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TypeMouvement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CommandeAchatId");

                    b.HasIndex("DateMouvement");

                    b.HasIndex("ProduitId");

                    b.ToTable("MouvementsStock");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SeuilMax")
                        .HasColumnType("int");

                    b.Property<int>("SeuilMin")
                        .HasColumnType("int");

                    b.Property<int>("StockActuel")
                        .HasColumnType("int");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.HasIndex("Reference");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Alerte", b =>
                {
                    b.HasOne("Gestion_Stock.Models.Produit", "Produit")
                        .WithMany("Alertes")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("Gestion_Stock.Models.CommandeAchat", b =>
                {
                    b.HasOne("Gestion_Stock.Models.Employe", "Employe")
                        .WithMany("Commandes")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Gestion_Stock.Models.Livraison", "Livraison")
                        .WithMany("Commandes")
                        .HasForeignKey("LivraisonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employe");

                    b.Navigation("Livraison");
                });

            modelBuilder.Entity("Gestion_Stock.Models.FournisseurProduit", b =>
                {
                    b.HasOne("Gestion_Stock.Models.Fournisseur", "Fournisseur")
                        .WithMany("FournisseurProduits")
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_Stock.Models.Produit", "Produit")
                        .WithMany("FournisseurProduits")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fournisseur");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("Gestion_Stock.Models.LigneCommande", b =>
                {
                    b.HasOne("Gestion_Stock.Models.CommandeAchat", "CommandeAchat")
                        .WithMany("LignesCommande")
                        .HasForeignKey("CommandeAchatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_Stock.Models.Produit", "Produit")
                        .WithMany("LignesCommande")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CommandeAchat");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Livraison", b =>
                {
                    b.HasOne("Gestion_Stock.Models.Commercial", "Commercial")
                        .WithMany("Livraisons")
                        .HasForeignKey("CommercialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Commercial");
                });

            modelBuilder.Entity("Gestion_Stock.Models.MouvementStock", b =>
                {
                    b.HasOne("Gestion_Stock.Models.CommandeAchat", "CommandeAchat")
                        .WithMany()
                        .HasForeignKey("CommandeAchatId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Gestion_Stock.Models.Produit", "Produit")
                        .WithMany("MouvementsStock")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommandeAchat");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Produit", b =>
                {
                    b.HasOne("Gestion_Stock.Models.Categorie", "Categorie")
                        .WithMany("Produits")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Categorie", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("Gestion_Stock.Models.CommandeAchat", b =>
                {
                    b.Navigation("LignesCommande");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Commercial", b =>
                {
                    b.Navigation("Livraisons");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Employe", b =>
                {
                    b.Navigation("Commandes");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Fournisseur", b =>
                {
                    b.Navigation("FournisseurProduits");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Livraison", b =>
                {
                    b.Navigation("Commandes");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Produit", b =>
                {
                    b.Navigation("Alertes");

                    b.Navigation("FournisseurProduits");

                    b.Navigation("LignesCommande");

                    b.Navigation("MouvementsStock");
                });
#pragma warning restore 612, 618
        }
    }
}
