// <auto-generated />
using System;
using Gestion_Stock.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestion_Stock.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260419015924_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gestion_Stock.Models.Alerte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstLue")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProduitId")
                        .HasColumnType("int");

                    b.Property<string>("TypeAlerte")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DateCreation");

                    b.HasIndex("ProduitId");

                    b.ToTable("Alertes");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Produits électroniques",
                            Nom = "Électronique"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Produits alimentaires",
                            Nom = "Alimentaire"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Articles vestimentaires",
                            Nom = "Vêtements"
                        });
                });

            modelBuilder.Entity("Gestion_Stock.Models.CommandeAchat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeId")
                        .HasColumnType("int");

                    b.Property<decimal>("FraisLivraison")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("LivraisonId")
                        .HasColumnType("int");

                    b.Property<decimal>("SousTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalFacture")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DateCommande");

                    b.HasIndex("EmployeId");

                    b.HasIndex("LivraisonId");

                    b.ToTable("CommandesAchat");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Commercial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Commission")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Commerciaux");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Commission = 5.5m,
                            Nom = "Pierre Durand",
                            Region = "Nord"
                        },
                        new
                        {
                            Id = 2,
                            Commission = 6.0m,
                            Nom = "Sophie Bernard",
                            Region = "Sud"
                        });
                });

            modelBuilder.Entity("Gestion_Stock.Models.Employe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Employes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "jean.dupont@gestionstock.com",
                            NomComplet = "Jean Dupont",
                            Note = "Responsable des achats"
                        },
                        new
                        {
                            Id = 2,
                            Email = "marie.martin@gestionstock.com",
                            NomComplet = "Marie Martin",
                            Note = "Gestionnaire de stock"
                        });
                });

            modelBuilder.Entity("Gestion_Stock.Models.Fournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Fournisseurs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresse = "123 Rue Tech",
                            Email = "contact@techsupply.com",
                            Nom = "TechSupply",
                            Telephone = "0123456789"
                        },
                        new
                        {
                            Id = 2,
                            Adresse = "456 Avenue Food",
                            Email = "info@fooddistrib.com",
                            Nom = "FoodDistrib",
                            Telephone = "0987654321"
                        });
                });

            modelBuilder.Entity("Gestion_Stock.Models.FournisseurProduit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DelaiLivraisonJours")
                        .HasColumnType("int");

                    b.Property<int>("FournisseurId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrixAchat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProduitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FournisseurId");

                    b.HasIndex("ProduitId");

                    b.ToTable("FournisseurProduits");
                });

            modelBuilder.Entity("Gestion_Stock.Models.LigneCommande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommandeAchatId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProduitId")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommandeAchatId");

                    b.HasIndex("ProduitId");

                    b.ToTable("LignesCommande");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Livraison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommercialId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateLivraison")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NoteAvis")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CommercialId");

                    b.ToTable("Livraisons");
                });

            modelBuilder.Entity("Gestion_Stock.Models.MouvementStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommandeAchatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateMouvement")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProduitId")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<string>("Raison")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TypeMouvement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CommandeAchatId");

                    b.HasIndex("DateMouvement");

                    b.HasIndex("ProduitId");

                    b.ToTable("MouvementsStock");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SeuilMax")
                        .HasColumnType("int");

                    b.Property<int>("SeuilMin")
                        .HasColumnType("int");

                    b.Property<int>("StockActuel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.HasIndex("Reference");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Alerte", b =>
                {
                    b.HasOne("Gestion_Stock.Models.Produit", "Produit")
                        .WithMany("Alertes")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("Gestion_Stock.Models.CommandeAchat", b =>
                {
                    b.HasOne("Gestion_Stock.Models.Employe", "Employe")
                        .WithMany("Commandes")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Gestion_Stock.Models.Livraison", "Livraison")
                        .WithMany("Commandes")
                        .HasForeignKey("LivraisonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employe");

                    b.Navigation("Livraison");
                });

            modelBuilder.Entity("Gestion_Stock.Models.FournisseurProduit", b =>
                {
                    b.HasOne("Gestion_Stock.Models.Fournisseur", "Fournisseur")
                        .WithMany("FournisseurProduits")
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_Stock.Models.Produit", "Produit")
                        .WithMany("FournisseurProduits")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fournisseur");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("Gestion_Stock.Models.LigneCommande", b =>
                {
                    b.HasOne("Gestion_Stock.Models.CommandeAchat", "CommandeAchat")
                        .WithMany("LignesCommande")
                        .HasForeignKey("CommandeAchatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_Stock.Models.Produit", "Produit")
                        .WithMany("LignesCommande")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CommandeAchat");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Livraison", b =>
                {
                    b.HasOne("Gestion_Stock.Models.Commercial", "Commercial")
                        .WithMany("Livraisons")
                        .HasForeignKey("CommercialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Commercial");
                });

            modelBuilder.Entity("Gestion_Stock.Models.MouvementStock", b =>
                {
                    b.HasOne("Gestion_Stock.Models.CommandeAchat", "CommandeAchat")
                        .WithMany()
                        .HasForeignKey("CommandeAchatId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Gestion_Stock.Models.Produit", "Produit")
                        .WithMany("MouvementsStock")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommandeAchat");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Produit", b =>
                {
                    b.HasOne("Gestion_Stock.Models.Categorie", "Categorie")
                        .WithMany("Produits")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Categorie", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("Gestion_Stock.Models.CommandeAchat", b =>
                {
                    b.Navigation("LignesCommande");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Commercial", b =>
                {
                    b.Navigation("Livraisons");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Employe", b =>
                {
                    b.Navigation("Commandes");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Fournisseur", b =>
                {
                    b.Navigation("FournisseurProduits");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Livraison", b =>
                {
                    b.Navigation("Commandes");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Produit", b =>
                {
                    b.Navigation("Alertes");

                    b.Navigation("FournisseurProduits");

                    b.Navigation("LignesCommande");

                    b.Navigation("MouvementsStock");
                });
#pragma warning restore 612, 618
        }
    }
}
