// <auto-generated />
using System;
using Gestion_Stock.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestion_Stock.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gestion_Stock.Models.Alerte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstLue")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProduitId")
                        .HasColumnType("int");

                    b.Property<string>("TypeAlerte")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DateCreation");

                    b.HasIndex("ProduitId");

                    b.ToTable("Alertes");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Café, thé, chocolat, infusions",
                            Nom = "Boissons chaudes"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lait, crème, beurre, fromages",
                            Nom = "Produits laitiers"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Farine, sucre, sel, riz, pâtes",
                            Nom = "Farines & Céréales"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Poulet, bœuf, jambon, merguez",
                            Nom = "Viandes & Charcuterie"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Légumes frais, fruits de saison",
                            Nom = "Fruits & Légumes"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Huile d'olive, vinaigre, épices, sauces",
                            Nom = "Huiles & Condiments"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Jus, sodas, eau minérale, sirops",
                            Nom = "Boissons froides"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Œufs, levure, chocolat, vanille",
                            Nom = "Pâtisserie & Desserts"
                        });
                });

            modelBuilder.Entity("Gestion_Stock.Models.CommandeAchat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeId")
                        .HasColumnType("int");

                    b.Property<int?>("FournisseurId")
                        .HasColumnType("int");

                    b.Property<decimal>("FraisLivraison")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("LivraisonId")
                        .HasColumnType("int");

                    b.Property<decimal>("MontantTVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("SousTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TauxTVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalFacture")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTTC")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DateCommande");

                    b.HasIndex("EmployeId");

                    b.HasIndex("FournisseurId");

                    b.HasIndex("LivraisonId");

                    b.ToTable("CommandesAchat");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Commercial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Commission")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("FournisseurId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("FournisseurId");

                    b.ToTable("Commerciaux");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Commission = 3.5m,
                            FournisseurId = 1,
                            Nom = "Karim Mansouri",
                            Region = "Grand Tunis"
                        },
                        new
                        {
                            Id = 2,
                            Commission = 4.0m,
                            FournisseurId = 2,
                            Nom = "Sonia Gharbi",
                            Region = "Sahel"
                        });
                });

            modelBuilder.Entity("Gestion_Stock.Models.Employe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Employes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ahmed.bensalah@cafe-resto.tn",
                            NomComplet = "Ahmed Ben Salah",
                            Note = "Responsable des achats et approvisionnement",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "fatma.trabelsi@cafe-resto.tn",
                            NomComplet = "Fatma Trabelsi",
                            Note = "Gestionnaire de stock et inventaire",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Email = "m.chaabane@cafe-resto.tn",
                            NomComplet = "Mohamed Chaabane",
                            Note = "Chef de cuisine - contrôle qualité",
                            Role = "ChefCuisine"
                        },
                        new
                        {
                            Id = 4,
                            Email = "s.mejri@cafe-resto.tn",
                            NomComplet = "Sarra Mejri",
                            Note = "Serveuse",
                            Role = "Serveur"
                        });
                });

            modelBuilder.Entity("Gestion_Stock.Models.Fournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Fournisseurs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresse = "Zone Industrielle, Tunis",
                            Email = "commandes@cafepremium.tn",
                            Nom = "Café Premium Tunisie",
                            Telephone = "71 234 567"
                        },
                        new
                        {
                            Id = 2,
                            Adresse = "Route de Bizerte, Mateur",
                            Email = "ventes@laiterie-nord.tn",
                            Nom = "Laiterie du Nord",
                            Telephone = "72 345 678"
                        },
                        new
                        {
                            Id = 3,
                            Adresse = "Marché de Gros, Sfax",
                            Email = "contact@grossiste-benali.tn",
                            Nom = "Grossiste Alimentaire Ben Ali",
                            Telephone = "73 456 789"
                        },
                        new
                        {
                            Id = 4,
                            Adresse = "Rue du Marché, Sousse",
                            Email = "info@boucherie-centrale.tn",
                            Nom = "Boucherie Centrale",
                            Telephone = "74 567 890"
                        });
                });

            modelBuilder.Entity("Gestion_Stock.Models.FournisseurProduit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DelaiLivraisonJours")
                        .HasColumnType("int");

                    b.Property<bool>("EstPrefere")
                        .HasColumnType("bit");

                    b.Property<int>("FournisseurId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrixAchat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProduitId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceFournisseur")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FournisseurId");

                    b.HasIndex("ProduitId");

                    b.ToTable("FournisseurProduits");
                });

            modelBuilder.Entity("Gestion_Stock.Models.LigneCommande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommandeAchatId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProduitId")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<int>("QuantiteRecue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommandeAchatId");

                    b.HasIndex("ProduitId");

                    b.ToTable("LignesCommande");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Livraison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommercialId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateLivraison")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstPartielle")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NoteAvis")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("NoteChiffre")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CommercialId");

                    b.ToTable("Livraisons");
                });

            modelBuilder.Entity("Gestion_Stock.Models.LogAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DateAction")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("EmployeId")
                        .HasColumnType("int");

                    b.Property<string>("Entite")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EntiteId")
                        .HasColumnType("int");

                    b.Property<string>("NomUtilisateur")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DateAction");

                    b.HasIndex("EmployeId");

                    b.ToTable("LogsActions");
                });

            modelBuilder.Entity("Gestion_Stock.Models.MouvementStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommandeAchatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateMouvement")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeId")
                        .HasColumnType("int");

                    b.Property<string>("Motif")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProduitId")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<string>("Raison")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TypeMouvement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CommandeAchatId");

                    b.HasIndex("DateMouvement");

                    b.HasIndex("EmployeId");

                    b.HasIndex("ProduitId");

                    b.ToTable("MouvementsStock");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SeuilMax")
                        .HasColumnType("int");

                    b.Property<int>("SeuilMin")
                        .HasColumnType("int");

                    b.Property<int>("StockActuel")
                        .HasColumnType("int");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.HasIndex("Reference");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Gestion_Stock.Models.Alerte", b =>
                {
                    b.HasOne("Gestion_Stock.Models.Produit", "Produit")
                        .WithMany("Alertes")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("Gestion_Stock.Models.CommandeAchat", b =>
                {
                    b.HasOne("Gestion_Stock.Models.Employe", "Employe")
                        .WithMany("Commandes")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Gestion_Stock.Models.Fournisseur", "Fournisseur")
                        .WithMany()
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Gestion_Stock.Models.Livraison", "Livraison")
                        .WithMany("Commandes")
                        .HasForeignKey("LivraisonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employe");

                    b.Navigation("Fournisseur");

                    b.Navigation("Livraison");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Commercial", b =>
                {
                    b.HasOne("Gestion_Stock.Models.Fournisseur", "Fournisseur")
                        .WithMany("Commerciaux")
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Fournisseur");
                });

            modelBuilder.Entity("Gestion_Stock.Models.FournisseurProduit", b =>
                {
                    b.HasOne("Gestion_Stock.Models.Fournisseur", "Fournisseur")
                        .WithMany("FournisseurProduits")
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_Stock.Models.Produit", "Produit")
                        .WithMany("FournisseurProduits")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fournisseur");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("Gestion_Stock.Models.LigneCommande", b =>
                {
                    b.HasOne("Gestion_Stock.Models.CommandeAchat", "CommandeAchat")
                        .WithMany("LignesCommande")
                        .HasForeignKey("CommandeAchatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_Stock.Models.Produit", "Produit")
                        .WithMany("LignesCommande")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CommandeAchat");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Livraison", b =>
                {
                    b.HasOne("Gestion_Stock.Models.Commercial", "Commercial")
                        .WithMany("Livraisons")
                        .HasForeignKey("CommercialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Commercial");
                });

            modelBuilder.Entity("Gestion_Stock.Models.LogAction", b =>
                {
                    b.HasOne("Gestion_Stock.Models.Employe", "Employe")
                        .WithMany("LogsActions")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employe");
                });

            modelBuilder.Entity("Gestion_Stock.Models.MouvementStock", b =>
                {
                    b.HasOne("Gestion_Stock.Models.CommandeAchat", "CommandeAchat")
                        .WithMany()
                        .HasForeignKey("CommandeAchatId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Gestion_Stock.Models.Employe", "Employe")
                        .WithMany()
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Gestion_Stock.Models.Produit", "Produit")
                        .WithMany("MouvementsStock")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommandeAchat");

                    b.Navigation("Employe");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Produit", b =>
                {
                    b.HasOne("Gestion_Stock.Models.Categorie", "Categorie")
                        .WithMany("Produits")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gestion_Stock.Models.Categorie", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("Gestion_Stock.Models.CommandeAchat", b =>
                {
                    b.Navigation("LignesCommande");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Commercial", b =>
                {
                    b.Navigation("Livraisons");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Employe", b =>
                {
                    b.Navigation("Commandes");

                    b.Navigation("LogsActions");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Fournisseur", b =>
                {
                    b.Navigation("Commerciaux");

                    b.Navigation("FournisseurProduits");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Livraison", b =>
                {
                    b.Navigation("Commandes");
                });

            modelBuilder.Entity("Gestion_Stock.Models.Produit", b =>
                {
                    b.Navigation("Alertes");

                    b.Navigation("FournisseurProduits");

                    b.Navigation("LignesCommande");

                    b.Navigation("MouvementsStock");
                });
#pragma warning restore 612, 618
        }
    }
}
